huboplus:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------

  # Left Hand Shoulder (Pitch, Roll, Yaw)
  joint_LSP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LSP
    pid: {p: 100, i: 0, d: 0}
  joint_LSR_position_controller:
    type: effort_controllers/JointPositionController
    joint: LSR
    pid: {p: 25, i: 0, d: 0.1}
  joint_LSY_position_controller:
    type: effort_controllers/JointPositionController
    joint: LSY
    pid: {p: 100, i: 0, d: 0}

  # Right Hand Shoulder (Pitch, Roll, Yaw)
  joint_RSP_position_controller:
    type: effort_controllers/JointPositionController
    joint: RSP
    pid: {p: 100, i: 0, d: 0}
  joint_RSR_position_controller:
    type: effort_controllers/JointPositionController
    joint: RSR
    pid: {p: 25, i: 0, d: 0.1}
  joint_RSY_position_controller:
    type: effort_controllers/JointPositionController
    joint: RSY
    pid: {p: 100, i: 0, d: 0}

  # Left And Right Elbow
  joint_LEP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LEP
    pid: {p: 50, i: 0, d: 0}
  joint_REP_position_controller:
    type: effort_controllers/JointPositionController
    joint: REP
    pid: {p: 50, i: 0, d: 0}

  # Left Wrist
  joint_LWY_position_controller:
    type: effort_controllers/JointPositionController
    joint: LWY
    pid: {p: 50, i: 0, d: 0}
  joint_LWP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LWP
    pid: {p: 50, i: 0, d: 0}

  # Right Wrist
  joint_RWY_position_controller:
    type: effort_controllers/JointPositionController
    joint: RWY
    pid: {p: 50, i: 0, d: 0}
  joint_RWP_position_controller:
    type: effort_controllers/JointPositionController
    joint: RWP
    pid: {p: 50, i: 0, d: 0}

  # Waist
  joint_WST_position_controller:
    type: effort_controllers/JointPositionController
    joint: WST
    pid: {p: 250, i: 0, d: 0}

  # Left Leg (Hip Yaw, Roll and Pitch; Knee Pitch; Ankle Pitch and Roll)
  joint_LHY_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHY
    pid: {p: 250, i: 0, d: 0.15}
  joint_LHR_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHR
    pid: {p: 575, i: 20, d: 0} # the original controller had integral limits
  joint_LHP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LHP
    pid: {p: 500, i: 0, d: 0.15}
  joint_LKP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LKP
    pid: {p: 200, i: 0, d: 0.15}
  joint_LAP_position_controller:
    type: effort_controllers/JointPositionController
    joint: LAP
    pid: {p: 500, i: 0, d: 0.15}
  joint_LAR_position_controller:
    type: effort_controllers/JointPositionController
    joint: LAR
    pid: {p: 390, i: 0, d: 0.1}

  # Right Leg (Hip Yaw, Roll and Pitch; Knee Pitch; Ankle Pitch and Roll)
  joint_RHY_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHY
    pid: {p: 250, i: 0, d: 0.15}
  joint_RHR_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHR
    pid: {p: 575, i: 20, d: 0} # the original controller had integral limits
  joint_RHP_position_controller:
    type: effort_controllers/JointPositionController
    joint: RHP
    pid: {p: 500, i: 0, d: 0.15}
  joint_RKP_position_controller:
    type: effort_controllers/JointPositionController
    joint: RKP
    pid: {p: 200, i: 0, d: 0.15}
  joint_RAP_position_controller:
    type: effort_controllers/JointPositionController
    joint: RAP
    pid: {p: 500, i: 0, d: 0.15}
  joint_RAR_position_controller:
    type: effort_controllers/JointPositionController
    joint: RAR
    pid: {p: 390, i: 0, d: 0.1}

  # Neck: Head Pitch (up and down)
  joint_HNP_position_controller:
    type: effort_controllers/JointPositionController
    joint: HNP
    pid: {p: 390, i: 0, d: 0.1}

