huboplus:

  # Publish all joint states -----------------------------------

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Trajectory Controllers -------------------------------------

  left_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [LSP, LSR, LSY, LEP, LWY, LWP]
    gains:
      LSP: {p: 2400, i: 800, d: 18}
      LSR: {p: 2400, i: 800, d: 18}
      LSY: {p: 1000, i: 600, d:  6}
      LEP: {p: 1000, i: 600, d:  6}
      LWY: {p: 1000, i: 600, d:  6}
      LWP: {p: 1000, i: 600, d:  6}

  right_hand_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [RSP, RSR, RSY, REP, RWY, RWP]
    gains:
      RSP: {p: 2400, i: 800, d: 18}
      RSR: {p: 2400, i: 800, d: 18}
      RSY: {p: 1000, i: 600, d:  6}
      REP: {p: 1000, i: 600, d:  6}
      RWY: {p: 1000, i: 600, d:  6}
      RWP: {p: 1000, i: 600, d:  6}

  legs_controller:
    type: effort_controllers/JointTrajectoryController
    joints: [LHY, LHR, LHP, LKP, LAP, LAR,
             RHY, RHR, RHP, RKP, RAP, RAR]
    gains:
      LHY: {p: 2400, i: 800, d: 18}
      LHR: {p: 2400, i: 800, d: 18}     # add integral limits from the original controller?
      LHP: {p: 2400, i: 800, d: 18}
      LKP: {p: 2400, i: 800, d: 18}
      LAP: {p: 2400, i: 800, d: 18}
      LAR: {p: 2400, i: 800, d: 18}
      RHY: {p: 2400, i: 800, d: 18}
      RHR: {p: 2400, i: 800, d: 18}     # add integral limits from the original controller?
      RHP: {p: 2400, i: 800, d: 18}
      RKP: {p: 2400, i: 800, d: 18}
      RAP: {p: 2400, i: 800, d: 18}
      RAR: {p: 2400, i: 800, d: 18}

  # Neck: Head Pitch (up and down)
  joint_HNP_position_controller:
    type: effort_controllers/JointPositionController
    joint: HNP
    pid: {p: 390, i: 0, d: 0.1}

  # Waist
  joint_WST_position_controller:
    type: effort_controllers/JointPositionController
    joint: WST
    pid: {p: 1000, i: 600, d: 6}

  # We would like to avoid these controllers and make
  # the corresponding joints fixed. However I was
  # not able to set up coordinate frames properly
  # without controllable joints. Necessary set point
  # values are documented in
  # hubo_control/launch/demo.launch
  joint_hand_sensor_controller0:
    type: effort_controllers/JointPositionController
    joint: hand_mount_prosilica_joint
    pid: {p: 390, i: 0, d: 0.1}
  joint_hand_sensor_controller_z:
    type: effort_controllers/JointPositionController
    joint: hand_mount_prosilica_optical_frame_joint_z
    pid: {p: 390, i: 0, d: 0.1}
  joint_hand_sensor_controller_y:
    type: effort_controllers/JointPositionController
    joint: hand_mount_prosilica_optical_frame_joint1
    pid: {p: 390, i: 0, d: 0.1}
  joint_hand_sensor_controller_x:
    type: effort_controllers/JointPositionController
    joint: hand_mount_prosilica_optical_frame_joint
    pid: {p: 390, i: 0, d: 0.1}
